name: 'doc ğŸ‡¯ğŸ‡µï¸'

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        version=dev
        ./substitute.sh ${version}
        docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make html BASEDIR=/doc\
          LOCALEDIR=/doc/locale SPHINXOPTS="-D language='ja'"
    - name: Archive build artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          build/html/**/*
